/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package setting;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import main.HomePage;
import main.Login;

/**
 *
 * @author mahad
 */
public class settingHomePage extends javax.swing.JFrame {

    Timer timer;
    
    public settingHomePage() {
        initComponents();
        ActionListener actionListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date date = new Date();
                DateFormat timeFormat = new SimpleDateFormat("hh:mm:ss aa");
                String time = timeFormat.format(date);
                curr_time_label.setText(time);
            }
        };
        timer = new Timer(1000, actionListener);
        timer.setInitialDelay(0);
        timer.start();
        setIconImage();
    }

    
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setting_panel = new javax.swing.JPanel();
        reception_setting_btn = new javax.swing.JButton();
        doc_setting_btn = new javax.swing.JButton();
        logo_label = new javax.swing.JLabel();
        bradcum_label = new javax.swing.JLabel();
        clock_label = new javax.swing.JLabel();
        curr_time_label = new javax.swing.JLabel();
        home_btn = new javax.swing.JButton();
        logOut_btn = new javax.swing.JButton();
        background_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Setting Window");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setResizable(false);

        setting_panel.setPreferredSize(new java.awt.Dimension(1050, 626));
        setting_panel.setLayout(null);

        reception_setting_btn.setBackground(new java.awt.Color(204, 204, 255));
        reception_setting_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        reception_setting_btn.setForeground(new java.awt.Color(102, 102, 102));
        reception_setting_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setting/receptionist.png"))); // NOI18N
        reception_setting_btn.setText("Reception Setting");
        reception_setting_btn.setToolTipText("Reception Setting");
        reception_setting_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reception_setting_btnActionPerformed(evt);
            }
        });
        setting_panel.add(reception_setting_btn);
        reception_setting_btn.setBounds(540, 130, 390, 210);

        doc_setting_btn.setBackground(new java.awt.Color(204, 204, 255));
        doc_setting_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        doc_setting_btn.setForeground(new java.awt.Color(102, 102, 102));
        doc_setting_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setting/doctor.png"))); // NOI18N
        doc_setting_btn.setText("Doctor Setting");
        doc_setting_btn.setToolTipText("Doctor Setting");
        doc_setting_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_setting_btnActionPerformed(evt);
            }
        });
        setting_panel.add(doc_setting_btn);
        doc_setting_btn.setBounds(110, 130, 390, 210);

        logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setting/help.png"))); // NOI18N
        setting_panel.add(logo_label);
        logo_label.setBounds(30, 20, 60, 50);

        bradcum_label.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 36)); // NOI18N
        bradcum_label.setForeground(new java.awt.Color(255, 255, 255));
        bradcum_label.setText("Setting Panel");
        setting_panel.add(bradcum_label);
        bradcum_label.setBounds(90, 30, 260, 40);

        clock_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Clock-Forward-icon.png"))); // NOI18N
        setting_panel.add(clock_label);
        clock_label.setBounds(430, 20, 48, 50);

        curr_time_label.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        curr_time_label.setForeground(new java.awt.Color(51, 51, 51));
        setting_panel.add(curr_time_label);
        curr_time_label.setBounds(480, 30, 160, 40);

        home_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        home_btn.setForeground(new java.awt.Color(102, 102, 102));
        home_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/Home-icon (1).png"))); // NOI18N
        home_btn.setText("Home");
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        setting_panel.add(home_btn);
        home_btn.setBounds(720, 20, 160, 57);

        logOut_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logOut_btn.setForeground(new java.awt.Color(102, 102, 102));
        logOut_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/switch-turn-off-icon.png"))); // NOI18N
        logOut_btn.setText("Log Out");
        logOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btnActionPerformed(evt);
            }
        });
        setting_panel.add(logOut_btn);
        logOut_btn.setBounds(880, 20, 160, 57);

        background_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setting/AllBackGrondPic.jpg"))); // NOI18N
        setting_panel.add(background_label);
        background_label.setBounds(0, 0, 1050, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(setting_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(setting_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        dispose();
    }//GEN-LAST:event_home_btnActionPerformed

    private void logOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btnActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOut_btnActionPerformed

    private void doc_setting_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_setting_btnActionPerformed
        DoctorSetting ds = new DoctorSetting();
        ds.setVisible(true);
        dispose();
    }//GEN-LAST:event_doc_setting_btnActionPerformed

    private void reception_setting_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reception_setting_btnActionPerformed
        RepSetting rs = new RepSetting();
        rs.setVisible(true);
        dispose();
    }//GEN-LAST:event_reception_setting_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(settingHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(settingHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(settingHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(settingHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new settingHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_label;
    private javax.swing.JLabel bradcum_label;
    private javax.swing.JLabel clock_label;
    private javax.swing.JLabel curr_time_label;
    private javax.swing.JButton doc_setting_btn;
    private javax.swing.JButton home_btn;
    private javax.swing.JButton logOut_btn;
    private javax.swing.JLabel logo_label;
    private javax.swing.JButton reception_setting_btn;
    private javax.swing.JPanel setting_panel;
    // End of variables declaration//GEN-END:variables
}
