/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nurse;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import main.HomePage;
import main.Login;

/**
 *
 * @author mahad
 */
public class nurseHomePage extends javax.swing.JFrame {

    Timer timer;
    public nurseHomePage() {
        initComponents();
        ActionListener actionListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date date = new Date();
                DateFormat timeFormat = new SimpleDateFormat("hh:mm:ss aa");
                String time = timeFormat.format(date);
                curr_time_label.setText(time);
            }
        };
        timer = new Timer(1000, actionListener);
        timer.setInitialDelay(0);
        timer.start();
        setIconImage();
    }
    
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nurse_panel = new javax.swing.JPanel();
        curr_time_label = new javax.swing.JLabel();
        page_title_label = new javax.swing.JLabel();
        home_btn = new javax.swing.JButton();
        add_btn2 = new javax.swing.JButton();
        update_btn2 = new javax.swing.JButton();
        delete_btn2 = new javax.swing.JButton();
        search_btn2 = new javax.swing.JButton();
        view_btn2 = new javax.swing.JButton();
        add_btn = new javax.swing.JButton();
        search_bnt = new javax.swing.JButton();
        view_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        logOut_btn2 = new javax.swing.JButton();
        time_label = new javax.swing.JLabel();
        logout_btn = new javax.swing.JButton();
        background_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nurse Window");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(1050, 626));

        nurse_panel.setPreferredSize(new java.awt.Dimension(1050, 626));
        nurse_panel.setLayout(null);

        curr_time_label.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        curr_time_label.setForeground(new java.awt.Color(102, 102, 102));
        nurse_panel.add(curr_time_label);
        curr_time_label.setBounds(870, 50, 170, 40);

        page_title_label.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 48)); // NOI18N
        page_title_label.setForeground(new java.awt.Color(255, 255, 255));
        page_title_label.setText("Nurse Panel");
        nurse_panel.add(page_title_label);
        page_title_label.setBounds(20, 30, 330, 70);

        home_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        home_btn.setForeground(new java.awt.Color(102, 102, 102));
        home_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/Home-icon (1).png"))); // NOI18N
        home_btn.setText("Home");
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        nurse_panel.add(home_btn);
        home_btn.setBounds(10, 140, 140, 60);

        add_btn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add_btn2.setForeground(new java.awt.Color(102, 102, 102));
        add_btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/Actions-contact-new-icon.png"))); // NOI18N
        add_btn2.setText("Add");
        add_btn2.setToolTipText("");
        add_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btn2ActionPerformed(evt);
            }
        });
        nurse_panel.add(add_btn2);
        add_btn2.setBounds(10, 200, 140, 60);

        update_btn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update_btn2.setForeground(new java.awt.Color(102, 102, 102));
        update_btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/document-edit-icon (1).png"))); // NOI18N
        update_btn2.setText("Update");
        update_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btn2ActionPerformed(evt);
            }
        });
        nurse_panel.add(update_btn2);
        update_btn2.setBounds(10, 260, 140, 60);

        delete_btn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete_btn2.setForeground(new java.awt.Color(102, 102, 102));
        delete_btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/close-icon (1).png"))); // NOI18N
        delete_btn2.setText("Delete");
        delete_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btn2ActionPerformed(evt);
            }
        });
        nurse_panel.add(delete_btn2);
        delete_btn2.setBounds(10, 320, 140, 60);

        search_btn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search_btn2.setForeground(new java.awt.Color(102, 102, 102));
        search_btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/search-icon (1).png"))); // NOI18N
        search_btn2.setText("Search");
        search_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btn2ActionPerformed(evt);
            }
        });
        nurse_panel.add(search_btn2);
        search_btn2.setBounds(10, 380, 140, 60);

        view_btn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        view_btn2.setForeground(new java.awt.Color(102, 102, 102));
        view_btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/Actions-view-pim-tasks-icon (1).png"))); // NOI18N
        view_btn2.setText("View");
        view_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_btn2ActionPerformed(evt);
            }
        });
        nurse_panel.add(view_btn2);
        view_btn2.setBounds(10, 440, 140, 60);

        add_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add_btn.setForeground(new java.awt.Color(102, 102, 102));
        add_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/Actions-contact-new-icon (1).png"))); // NOI18N
        add_btn.setText("Add");
        add_btn.setToolTipText("Add Doctor");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        nurse_panel.add(add_btn);
        add_btn.setBounds(220, 200, 250, 140);

        search_bnt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        search_bnt.setForeground(new java.awt.Color(102, 102, 102));
        search_bnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/search-icon.png"))); // NOI18N
        search_bnt.setText("Search");
        search_bnt.setToolTipText("Search Doctor");
        search_bnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_bntActionPerformed(evt);
            }
        });
        nurse_panel.add(search_bnt);
        search_bnt.setBounds(220, 370, 250, 140);

        view_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        view_btn.setForeground(new java.awt.Color(102, 102, 102));
        view_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/Actions-view-pim-tasks-icon.png"))); // NOI18N
        view_btn.setText("View");
        view_btn.setToolTipText("View Docor");
        view_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_btnActionPerformed(evt);
            }
        });
        nurse_panel.add(view_btn);
        view_btn.setBounds(490, 370, 250, 140);

        update_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        update_btn.setForeground(new java.awt.Color(102, 102, 102));
        update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/document-edit-icon.png"))); // NOI18N
        update_btn.setText("Update");
        update_btn.setToolTipText("Update Doctor");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        nurse_panel.add(update_btn);
        update_btn.setBounds(490, 200, 250, 140);

        delete_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(102, 102, 102));
        delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/close-icon.png"))); // NOI18N
        delete_btn.setText("Delete");
        delete_btn.setToolTipText("Delete Doctor");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        nurse_panel.add(delete_btn);
        delete_btn.setBounds(760, 200, 250, 140);

        logOut_btn2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        logOut_btn2.setForeground(new java.awt.Color(102, 102, 102));
        logOut_btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/switch-turn-off-icon (1).png"))); // NOI18N
        logOut_btn2.setText("Logout");
        logOut_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btn2ActionPerformed(evt);
            }
        });
        nurse_panel.add(logOut_btn2);
        logOut_btn2.setBounds(760, 370, 250, 140);

        time_label.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        time_label.setForeground(new java.awt.Color(102, 102, 102));
        time_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/Clock-Forward-icon.png"))); // NOI18N
        nurse_panel.add(time_label);
        time_label.setBounds(810, 40, 60, 50);

        logout_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(102, 102, 102));
        logout_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/switch-turn-off-icon.png"))); // NOI18N
        logout_btn.setText("LogOut");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        nurse_panel.add(logout_btn);
        logout_btn.setBounds(10, 500, 140, 60);

        background_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nurse/AllBackGrondPic.jpg"))); // NOI18N
        background_label.setPreferredSize(new java.awt.Dimension(1050, 626));
        nurse_panel.add(background_label);
        background_label.setBounds(0, 0, 1050, 626);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nurse_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nurse_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        dispose();
    }//GEN-LAST:event_home_btnActionPerformed

    private void add_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btn2ActionPerformed
        AddNurse an = new AddNurse();
        an.setVisible(true);
        dispose();
    }//GEN-LAST:event_add_btn2ActionPerformed

    private void update_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btn2ActionPerformed
        UpdateNurse un = new UpdateNurse();
        un.setVisible(true);
        dispose();
    }//GEN-LAST:event_update_btn2ActionPerformed

    private void delete_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btn2ActionPerformed
        DeleteNurse dn = new DeleteNurse();
        dn.setVisible(true);
        dispose();
    }//GEN-LAST:event_delete_btn2ActionPerformed

    private void search_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btn2ActionPerformed
        SearchNurse np = new SearchNurse();
        np.setVisible(true);
        dispose();
    }//GEN-LAST:event_search_btn2ActionPerformed

    private void view_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btn2ActionPerformed
        ViewNurse vn = new ViewNurse();
        vn.setVisible(true);
        dispose();
    }//GEN-LAST:event_view_btn2ActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        AddNurse an = new AddNurse();
        an.setVisible(true);
        dispose();
    }//GEN-LAST:event_add_btnActionPerformed

    private void search_bntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_bntActionPerformed
        SearchNurse np = new SearchNurse();
        np.setVisible(true);
        dispose();
    }//GEN-LAST:event_search_bntActionPerformed

    private void view_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btnActionPerformed
        ViewNurse vn = new ViewNurse();
        vn.setVisible(true);
        dispose();
    }//GEN-LAST:event_view_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        UpdateNurse un = new UpdateNurse();
        un.setVisible(true);
        dispose();
    }//GEN-LAST:event_update_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        DeleteNurse dn = new DeleteNurse();
        dn.setVisible(true);
        dispose();
    }//GEN-LAST:event_delete_btnActionPerformed

    private void logOut_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btn2ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOut_btn2ActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logout_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nurseHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nurseHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nurseHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nurseHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nurseHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JButton add_btn2;
    private javax.swing.JLabel background_label;
    private javax.swing.JLabel curr_time_label;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton delete_btn2;
    private javax.swing.JButton home_btn;
    private javax.swing.JButton logOut_btn2;
    private javax.swing.JButton logout_btn;
    private javax.swing.JPanel nurse_panel;
    private javax.swing.JLabel page_title_label;
    private javax.swing.JButton search_bnt;
    private javax.swing.JButton search_btn2;
    private javax.swing.JLabel time_label;
    private javax.swing.JButton update_btn;
    private javax.swing.JButton update_btn2;
    private javax.swing.JButton view_btn;
    private javax.swing.JButton view_btn2;
    // End of variables declaration//GEN-END:variables
}
