/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nurse;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import main.Connector;
import main.HomePage;
import main.Login;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author mahad
 */
public class SearchNurse extends javax.swing.JFrame {

    private Connection conn;
    private PreparedStatement pst;
    private ResultSet rs;
    
    public SearchNurse() {
        initComponents();
        fetch_table();
        setIconImage();
    }
    
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    private void fetch_table(){
        try{
            conn = Connector.ConnectDB();
            String sql = "SELECT * FROM nurse";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            nurse_table.setModel(DbUtils.resultSetToTableModel(rs));
            nurse_table.setAutoResizeMode(nurse_table.AUTO_RESIZE_OFF);
            nurse_table.getColumnModel().getColumn(0).setPreferredWidth(70);
            nurse_table.getColumnModel().getColumn(1).setPreferredWidth(200);
            nurse_table.getColumnModel().getColumn(2).setPreferredWidth(160);
            nurse_table.getColumnModel().getColumn(3).setPreferredWidth(90);
            nurse_table.getColumnModel().getColumn(4).setPreferredWidth(40);
            nurse_table.getColumnModel().getColumn(5).setPreferredWidth(53);
            nurse_table.getColumnModel().getColumn(6).setPreferredWidth(231);
            nurse_table.getColumnModel().getColumn(7).setPreferredWidth(80);
            nurse_table.getColumnModel().getColumn(8).setPreferredWidth(40);
            nurse_table.getColumnModel().getColumn(9).setPreferredWidth(60);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search_window = new javax.swing.JPanel();
        table = new javax.swing.JScrollPane();
        nurse_table = new javax.swing.JTable();
        bradcum_label = new javax.swing.JLabel();
        search_txt = new javax.swing.JTextField();
        search_label = new javax.swing.JLabel();
        reload_label = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        home_btn = new javax.swing.JButton();
        logOut_btn = new javax.swing.JButton();
        bg_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search Window");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(1050, 626));

        search_window.setPreferredSize(new java.awt.Dimension(1050, 626));
        search_window.setLayout(null);

        nurse_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        table.setViewportView(nurse_table);

        search_window.add(table);
        table.setBounds(10, 160, 1030, 402);

        bradcum_label.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        bradcum_label.setForeground(new java.awt.Color(255, 255, 255));
        bradcum_label.setText("Nurse Panel >> Search Nurse");
        search_window.add(bradcum_label);
        bradcum_label.setBounds(10, 30, 530, 70);

        search_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search_txt.setForeground(new java.awt.Color(51, 51, 51));
        search_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_txtKeyReleased(evt);
            }
        });
        search_window.add(search_txt);
        search_txt.setBounds(60, 110, 410, 45);

        search_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/search-icon (1).png"))); // NOI18N
        search_window.add(search_label);
        search_label.setBounds(10, 100, 50, 60);

        reload_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/Arrow-reload-2-icon.png"))); // NOI18N
        reload_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reload_labelMouseClicked(evt);
            }
        });
        search_window.add(reload_label);
        reload_label.setBounds(480, 100, 70, 60);

        back_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(102, 102, 102));
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/arrow-back-icon.png"))); // NOI18N
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        search_window.add(back_btn);
        back_btn.setBounds(560, 100, 160, 60);

        home_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        home_btn.setForeground(new java.awt.Color(102, 102, 102));
        home_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/Home-icon (1).png"))); // NOI18N
        home_btn.setText("Home");
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        search_window.add(home_btn);
        home_btn.setBounds(720, 100, 160, 60);

        logOut_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logOut_btn.setForeground(new java.awt.Color(102, 102, 102));
        logOut_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/switch-turn-off-icon.png"))); // NOI18N
        logOut_btn.setText("Log Out");
        logOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btnActionPerformed(evt);
            }
        });
        search_window.add(logOut_btn);
        logOut_btn.setBounds(880, 100, 160, 60);

        bg_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nurse/AllBackGrondPic.jpg"))); // NOI18N
        search_window.add(bg_label);
        bg_label.setBounds(0, 0, 1050, 626);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(search_window, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(search_window, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_txtKeyReleased
        conn = Connector.ConnectDB();
        try{
            String sql = "SELECT * FROM nurse WHERE Name = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, search_txt.getText());
            rs = pst.executeQuery();
            nurse_table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        nurse_table.setAutoResizeMode(nurse_table.AUTO_RESIZE_OFF);
        nurse_table.getColumnModel().getColumn(0).setPreferredWidth(70);
        nurse_table.getColumnModel().getColumn(1).setPreferredWidth(200);
        nurse_table.getColumnModel().getColumn(2).setPreferredWidth(160);
        nurse_table.getColumnModel().getColumn(3).setPreferredWidth(90);
        nurse_table.getColumnModel().getColumn(4).setPreferredWidth(40);
        nurse_table.getColumnModel().getColumn(5).setPreferredWidth(53);
        nurse_table.getColumnModel().getColumn(6).setPreferredWidth(231);
        nurse_table.getColumnModel().getColumn(7).setPreferredWidth(80);
        nurse_table.getColumnModel().getColumn(8).setPreferredWidth(40);
        nurse_table.getColumnModel().getColumn(9).setPreferredWidth(60);
    }//GEN-LAST:event_search_txtKeyReleased

    private void reload_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reload_labelMouseClicked
        // TODO add your handling code here:
        search_txt.setText("");
    }//GEN-LAST:event_reload_labelMouseClicked

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        nurseHomePage nhp = new nurseHomePage();
        nhp.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        dispose();
    }//GEN-LAST:event_home_btnActionPerformed

    private void logOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btnActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOut_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchNurse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchNurse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchNurse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchNurse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchNurse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel bg_label;
    private javax.swing.JLabel bradcum_label;
    private javax.swing.JButton home_btn;
    private javax.swing.JButton logOut_btn;
    private javax.swing.JTable nurse_table;
    private javax.swing.JLabel reload_label;
    private javax.swing.JLabel search_label;
    private javax.swing.JTextField search_txt;
    private javax.swing.JPanel search_window;
    private javax.swing.JScrollPane table;
    // End of variables declaration//GEN-END:variables
}
