/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package about;


import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import main.HomePage;
import main.Login;

/**
 *
 * @author mahad
 */
public class aboutPage extends javax.swing.JFrame {

    Timer timer;
    
    public aboutPage() {
        initComponents();
        ActionListener actionListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date date = new Date();
                DateFormat timeFormat = new SimpleDateFormat("hh:mm:ss aa");
                String time = timeFormat.format(date);
                curr_time_label.setText(time);
            }
        };
        timer = new Timer(1000, actionListener);
        timer.setInitialDelay(0);
        timer.start();
        setIconImage();
    }
    
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        about_panel = new javax.swing.JPanel();
        text6 = new javax.swing.JLabel();
        text7 = new javax.swing.JLabel();
        text8 = new javax.swing.JLabel();
        text9 = new javax.swing.JLabel();
        text10 = new javax.swing.JLabel();
        text11 = new javax.swing.JLabel();
        text4 = new javax.swing.JLabel();
        text5 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        clock_label = new javax.swing.JLabel();
        curr_time_label = new javax.swing.JLabel();
        hospitalLogoTitle_label1 = new javax.swing.JLabel();
        hospitalLogoTitle_label = new javax.swing.JLabel();
        hospitalLogo_label = new javax.swing.JLabel();
        home_btn = new javax.swing.JButton();
        logOut_btn = new javax.swing.JButton();
        Background_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setResizable(false);

        about_panel.setPreferredSize(new java.awt.Dimension(1050, 626));
        about_panel.setLayout(null);

        text6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text6.setForeground(new java.awt.Color(102, 102, 102));
        text6.setText("through consistent commitment to improving the lives of people through utmost service excellence since its inception on 16th December 2006");
        about_panel.add(text6);
        text6.setBounds(10, 510, 1030, 20);

        text7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text7.setForeground(new java.awt.Color(102, 102, 102));
        text7.setText("Green Life Hospitals Limited is a 400 beds tertiary care hospital and the leading contributor of private healthcare services in Bangladesh. This has been achieved only ");
        about_panel.add(text7);
        text7.setBounds(10, 480, 1030, 20);

        text8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text8.setForeground(new java.awt.Color(102, 102, 102));
        text8.setText("through consistent commitment to improving the lives of people through utmost service excellence since its inception on 16th December 2006");
        about_panel.add(text8);
        text8.setBounds(10, 440, 1030, 20);

        text9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text9.setForeground(new java.awt.Color(102, 102, 102));
        text9.setText("Green Life Hospitals Limited is a 400 beds tertiary care hospital and the leading contributor of private healthcare services in Bangladesh. This has been achieved only ");
        about_panel.add(text9);
        text9.setBounds(10, 410, 1030, 20);

        text10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text10.setForeground(new java.awt.Color(102, 102, 102));
        text10.setText("through consistent commitment to improving the lives of people through utmost service excellence since its inception on 16th December 2006");
        about_panel.add(text10);
        text10.setBounds(10, 380, 1030, 20);

        text11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text11.setForeground(new java.awt.Color(102, 102, 102));
        text11.setText("Green Life Hospitals Limited is a 400 beds tertiary care hospital and the leading contributor of private healthcare services in Bangladesh. This has been achieved only ");
        about_panel.add(text11);
        text11.setBounds(10, 350, 1030, 20);

        text4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text4.setForeground(new java.awt.Color(102, 102, 102));
        text4.setText("through consistent commitment to improving the lives of people through utmost service excellence since its inception on 16th December 2006");
        about_panel.add(text4);
        text4.setBounds(10, 280, 1030, 20);

        text5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text5.setForeground(new java.awt.Color(102, 102, 102));
        text5.setText("Green Life Hospitals Limited is a 400 beds tertiary care hospital and the leading contributor of private healthcare services in Bangladesh. This has been achieved only ");
        about_panel.add(text5);
        text5.setBounds(10, 250, 1030, 20);

        text2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text2.setForeground(new java.awt.Color(102, 102, 102));
        text2.setText("through consistent commitment to improving the lives of people through utmost service excellence since its inception on 16th December 2006");
        about_panel.add(text2);
        text2.setBounds(10, 210, 1030, 20);

        text3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text3.setForeground(new java.awt.Color(102, 102, 102));
        text3.setText("Green Life Hospitals Limited is a 400 beds tertiary care hospital and the leading contributor of private healthcare services in Bangladesh. This has been achieved only ");
        about_panel.add(text3);
        text3.setBounds(10, 180, 1030, 20);

        text.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text.setForeground(new java.awt.Color(102, 102, 102));
        text.setText("through consistent commitment to improving the lives of people through utmost service excellence since its inception on 16th December 2006");
        about_panel.add(text);
        text.setBounds(10, 150, 1030, 20);

        text1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text1.setForeground(new java.awt.Color(102, 102, 102));
        text1.setText("Green Life Hospitals Limited is a 400 beds tertiary care hospital and the leading contributor of private healthcare services in Bangladesh. This has been achieved only ");
        about_panel.add(text1);
        text1.setBounds(10, 124, 1030, 20);

        clock_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Clock-Forward-icon.png"))); // NOI18N
        about_panel.add(clock_label);
        clock_label.setBounds(350, 30, 48, 50);

        curr_time_label.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        curr_time_label.setForeground(new java.awt.Color(51, 51, 51));
        about_panel.add(curr_time_label);
        curr_time_label.setBounds(400, 40, 160, 40);

        hospitalLogoTitle_label1.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        hospitalLogoTitle_label1.setForeground(new java.awt.Color(102, 102, 102));
        hospitalLogoTitle_label1.setText("Hospital");
        about_panel.add(hospitalLogoTitle_label1);
        hospitalLogoTitle_label1.setBounds(60, 50, 110, 30);

        hospitalLogoTitle_label.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        hospitalLogoTitle_label.setForeground(new java.awt.Color(102, 102, 102));
        hospitalLogoTitle_label.setText("Green Life");
        about_panel.add(hospitalLogoTitle_label);
        hospitalLogoTitle_label.setBounds(60, 30, 110, 20);

        hospitalLogo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hospital-icon.png"))); // NOI18N
        about_panel.add(hospitalLogo_label);
        hospitalLogo_label.setBounds(10, 30, 50, 48);

        home_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        home_btn.setForeground(new java.awt.Color(102, 102, 102));
        home_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/Home-icon (1).png"))); // NOI18N
        home_btn.setText("Home");
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        about_panel.add(home_btn);
        home_btn.setBounds(720, 20, 160, 60);

        logOut_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logOut_btn.setForeground(new java.awt.Color(102, 102, 102));
        logOut_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/switch-turn-off-icon.png"))); // NOI18N
        logOut_btn.setText("Log Out");
        logOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btnActionPerformed(evt);
            }
        });
        about_panel.add(logOut_btn);
        logOut_btn.setBounds(880, 20, 160, 60);

        Background_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about/AllBackGrondPic - Copy.jpg"))); // NOI18N
        about_panel.add(Background_label);
        Background_label.setBounds(0, 0, 1050, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(about_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(about_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        dispose();
    }//GEN-LAST:event_home_btnActionPerformed

    private void logOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btnActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOut_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aboutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aboutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aboutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aboutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aboutPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background_label;
    private javax.swing.JPanel about_panel;
    private javax.swing.JLabel clock_label;
    private javax.swing.JLabel curr_time_label;
    private javax.swing.JButton home_btn;
    private javax.swing.JLabel hospitalLogoTitle_label;
    private javax.swing.JLabel hospitalLogoTitle_label1;
    private javax.swing.JLabel hospitalLogo_label;
    private javax.swing.JButton logOut_btn;
    private javax.swing.JLabel text;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text10;
    private javax.swing.JLabel text11;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel text4;
    private javax.swing.JLabel text5;
    private javax.swing.JLabel text6;
    private javax.swing.JLabel text7;
    private javax.swing.JLabel text8;
    private javax.swing.JLabel text9;
    // End of variables declaration//GEN-END:variables
}
