/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
//import javax.swing.*;
//import java.awt.*;

import about.aboutPage;
import doctor.DoctorHomePage;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import lab.LabHomePage;
import nurse.nurseHomePage;
import patient.patientHomePage;
import reception.receptionHomePage;
import setting.settingHomePage;

//import java.awt.Event.*;

/**
 *
 * @author mahad
 */


public final class HomePage extends javax.swing.JFrame {

    Timer timer;
    public HomePage() {
        initComponents();
        //starting the time shower...
        ActionListener actionListener = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) { 
                Date date = new Date();
                DateFormat timeFormat = new SimpleDateFormat("hh:mm:ss aa");
                String time = timeFormat.format(date);
                curr_time_label.setText(time);
            }
            
        };
        timer = new Timer(1000, actionListener);
        timer.setInitialDelay(0);
        timer.start();
        //end of the time shower
        
        setIconImage();
    }
    
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        HomePanel = new javax.swing.JPanel();
        clock_label = new javax.swing.JLabel();
        hospitalLogoTitle_label1 = new javax.swing.JLabel();
        hospitalLogoTitle_label = new javax.swing.JLabel();
        hospitalLogo_label = new javax.swing.JLabel();
        title_label = new javax.swing.JLabel();
        logOut_btn = new javax.swing.JButton();
        Calendar = new com.toedter.calendar.JCalendar();
        rep_btn = new javax.swing.JButton();
        doc_btn = new javax.swing.JButton();
        nur_btn = new javax.swing.JButton();
        patient_btn = new javax.swing.JButton();
        lap_btn = new javax.swing.JButton();
        settign_btn = new javax.swing.JButton();
        About_btn = new javax.swing.JButton();
        curr_time_label = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        project_label = new javax.swing.JLabel();
        developer_label = new javax.swing.JLabel();
        roll_label = new javax.swing.JLabel();
        plot_label = new javax.swing.JLabel();
        batch_label = new javax.swing.JLabel();
        bc_label = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Window");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(1050, 626));

        HomePanel.setBackground(new java.awt.Color(255, 255, 255));
        HomePanel.setPreferredSize(new java.awt.Dimension(1050, 626));
        HomePanel.setLayout(null);

        clock_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Clock-Forward-icon.png"))); // NOI18N
        HomePanel.add(clock_label);
        clock_label.setBounds(20, 100, 48, 50);

        hospitalLogoTitle_label1.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        hospitalLogoTitle_label1.setForeground(new java.awt.Color(102, 102, 102));
        hospitalLogoTitle_label1.setText("Hospital");
        HomePanel.add(hospitalLogoTitle_label1);
        hospitalLogoTitle_label1.setBounds(60, 50, 110, 30);

        hospitalLogoTitle_label.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        hospitalLogoTitle_label.setForeground(new java.awt.Color(102, 102, 102));
        hospitalLogoTitle_label.setText("Chakoria Govt");
        HomePanel.add(hospitalLogoTitle_label);
        hospitalLogoTitle_label.setBounds(60, 30, 110, 20);

        hospitalLogo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hospital-icon.png"))); // NOI18N
        HomePanel.add(hospitalLogo_label);
        hospitalLogo_label.setBounds(10, 30, 50, 48);

        title_label.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 36)); // NOI18N
        title_label.setForeground(new java.awt.Color(102, 102, 102));
        title_label.setText("Welcome To Hospital Management System");
        HomePanel.add(title_label);
        title_label.setBounds(210, 10, 810, 80);

        logOut_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logOut_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/switch-turn-off-icon.png"))); // NOI18N
        logOut_btn.setText("LogOut");
        logOut_btn.setToolTipText("Log Out Button");
        logOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btnActionPerformed(evt);
            }
        });
        HomePanel.add(logOut_btn);
        logOut_btn.setBounds(880, 90, 160, 60);

        Calendar.setBackground(new java.awt.Color(255, 255, 255));
        Calendar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HomePanel.add(Calendar);
        Calendar.setBounds(180, 370, 450, 220);

        rep_btn.setBackground(new java.awt.Color(204, 204, 204));
        rep_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rep_btn.setForeground(new java.awt.Color(51, 51, 51));
        rep_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/receptionist.png"))); // NOI18N
        rep_btn.setText("Receptionist");
        rep_btn.setBorder(null);
        rep_btn.setBorderPainted(false);
        rep_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep_btnActionPerformed(evt);
            }
        });
        HomePanel.add(rep_btn);
        rep_btn.setBounds(10, 230, 160, 60);

        doc_btn.setBackground(new java.awt.Color(204, 204, 204));
        doc_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        doc_btn.setForeground(new java.awt.Color(51, 51, 51));
        doc_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/doctor.png"))); // NOI18N
        doc_btn.setText("Doctor");
        doc_btn.setBorder(null);
        doc_btn.setBorderPainted(false);
        doc_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_btnActionPerformed(evt);
            }
        });
        HomePanel.add(doc_btn);
        doc_btn.setBounds(10, 170, 160, 60);

        nur_btn.setBackground(new java.awt.Color(204, 204, 204));
        nur_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nur_btn.setForeground(new java.awt.Color(51, 51, 51));
        nur_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nurse.png"))); // NOI18N
        nur_btn.setText("Nurse");
        nur_btn.setBorder(null);
        nur_btn.setBorderPainted(false);
        nur_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nur_btnActionPerformed(evt);
            }
        });
        HomePanel.add(nur_btn);
        nur_btn.setBounds(10, 290, 160, 60);

        patient_btn.setBackground(new java.awt.Color(204, 204, 204));
        patient_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        patient_btn.setForeground(new java.awt.Color(51, 51, 51));
        patient_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/patient.png"))); // NOI18N
        patient_btn.setText("Patient");
        patient_btn.setBorder(null);
        patient_btn.setBorderPainted(false);
        patient_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patient_btnActionPerformed(evt);
            }
        });
        HomePanel.add(patient_btn);
        patient_btn.setBounds(10, 350, 160, 60);

        lap_btn.setBackground(new java.awt.Color(204, 204, 204));
        lap_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lap_btn.setForeground(new java.awt.Color(51, 51, 51));
        lap_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/microscope.png"))); // NOI18N
        lap_btn.setText("Laboratorist");
        lap_btn.setToolTipText("Laboratorist Button");
        lap_btn.setBorder(null);
        lap_btn.setBorderPainted(false);
        lap_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lap_btnActionPerformed(evt);
            }
        });
        HomePanel.add(lap_btn);
        lap_btn.setBounds(10, 410, 160, 60);

        settign_btn.setBackground(new java.awt.Color(204, 204, 204));
        settign_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        settign_btn.setForeground(new java.awt.Color(51, 51, 51));
        settign_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/help.png"))); // NOI18N
        settign_btn.setText("Setting");
        settign_btn.setToolTipText("Setting Button");
        settign_btn.setBorder(null);
        settign_btn.setBorderPainted(false);
        settign_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settign_btnActionPerformed(evt);
            }
        });
        HomePanel.add(settign_btn);
        settign_btn.setBounds(10, 470, 160, 60);

        About_btn.setBackground(new java.awt.Color(204, 204, 204));
        About_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        About_btn.setForeground(new java.awt.Color(51, 51, 51));
        About_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/about-us.png"))); // NOI18N
        About_btn.setText("About Us");
        About_btn.setToolTipText("About Button");
        About_btn.setBorder(null);
        About_btn.setBorderPainted(false);
        About_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                About_btnActionPerformed(evt);
            }
        });
        HomePanel.add(About_btn);
        About_btn.setBounds(10, 530, 160, 60);

        curr_time_label.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        curr_time_label.setForeground(new java.awt.Color(51, 51, 51));
        HomePanel.add(curr_time_label);
        curr_time_label.setBounds(70, 110, 160, 40);

        jInternalFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame1.setTitle("About Project");
        jInternalFrame1.setVisible(true);

        project_label.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        project_label.setForeground(new java.awt.Color(102, 102, 102));
        project_label.setText("Project : Hospital Management System");

        developer_label.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        developer_label.setForeground(new java.awt.Color(102, 102, 102));
        developer_label.setText("Developer : Md.Fazlay Rabby");

        roll_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roll_label.setForeground(new java.awt.Color(102, 102, 102));
        roll_label.setText("Batch:44");

        plot_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        plot_label.setForeground(new java.awt.Color(102, 102, 102));
        plot_label.setText("Tools : Netbeans, xamp (Java Swing With MySql)");

        batch_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        batch_label.setForeground(new java.awt.Color(102, 102, 102));
        batch_label.setText("id:162-15-8231");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(batch_label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roll_label)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plot_label, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(developer_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(project_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addComponent(project_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(developer_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(plot_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(batch_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roll_label, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        batch_label.getAccessibleContext().setAccessibleParent(HomePanel);

        HomePanel.add(jInternalFrame1);
        jInternalFrame1.setBounds(640, 370, 400, 220);

        bc_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/AllBackGrondPic.jpg"))); // NOI18N
        HomePanel.add(bc_label);
        bc_label.setBounds(0, 0, 1050, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void doc_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_btnActionPerformed
        DoctorHomePage doctorHomePage = new DoctorHomePage();
        doctorHomePage.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_doc_btnActionPerformed

    private void rep_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep_btnActionPerformed
        receptionHomePage rhp = new receptionHomePage();
        rhp.setVisible(true);
        dispose();

       
    }//GEN-LAST:event_rep_btnActionPerformed

    private void nur_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nur_btnActionPerformed
        nurseHomePage nhp = new nurseHomePage();
        nhp.setVisible(true);
        dispose();
    }//GEN-LAST:event_nur_btnActionPerformed

    private void patient_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patient_btnActionPerformed
        patientHomePage php = new patientHomePage();
        php.setVisible(true);
        dispose();
    }//GEN-LAST:event_patient_btnActionPerformed

    private void lap_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lap_btnActionPerformed
        LabHomePage lhp = new LabHomePage();
        lhp.setVisible(true);
        dispose();
    }//GEN-LAST:event_lap_btnActionPerformed

    private void settign_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settign_btnActionPerformed
        settingHomePage shp = new settingHomePage();
        shp.setVisible(true);
        dispose();
    }//GEN-LAST:event_settign_btnActionPerformed

    private void About_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_About_btnActionPerformed
        aboutPage ap = new aboutPage();
        ap.setVisible(true);
        dispose();
      
    }//GEN-LAST:event_About_btnActionPerformed
   
            
    private void logOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btnActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOut_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HomePage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton About_btn;
    private com.toedter.calendar.JCalendar Calendar;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JLabel batch_label;
    private javax.swing.JLabel bc_label;
    private javax.swing.JLabel clock_label;
    private javax.swing.JLabel curr_time_label;
    private javax.swing.JLabel developer_label;
    private javax.swing.JButton doc_btn;
    private javax.swing.JLabel hospitalLogoTitle_label;
    private javax.swing.JLabel hospitalLogoTitle_label1;
    private javax.swing.JLabel hospitalLogo_label;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton lap_btn;
    private javax.swing.JButton logOut_btn;
    private javax.swing.JButton nur_btn;
    private javax.swing.JButton patient_btn;
    private javax.swing.JLabel plot_label;
    private javax.swing.JLabel project_label;
    private javax.swing.JButton rep_btn;
    private javax.swing.JLabel roll_label;
    private javax.swing.JButton settign_btn;
    private javax.swing.JLabel title_label;
    // End of variables declaration//GEN-END:variables
}
