/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;



/**
 *
 * @author mahad
 */
public class Login extends javax.swing.JFrame {

    private Connection conn = null;
    private PreparedStatement pst = null;
    private ResultSet rs = null;
    
    public Login() {
        initComponents();
        setIconImage();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        title_label = new javax.swing.JLabel();
        logbutton_label = new javax.swing.JLabel();
        pass_label = new javax.swing.JLabel();
        user_label = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        txt_password = new javax.swing.JPasswordField();
        txt_username = new javax.swing.JTextField();
        backgournd_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In Window");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setPreferredSize(new java.awt.Dimension(1050, 626));
        setResizable(false);

        Panel1.setPreferredSize(new java.awt.Dimension(1050, 626));
        Panel1.setLayout(null);

        title_label.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        title_label.setText("Hospital Management System");
        Panel1.add(title_label);
        title_label.setBounds(270, 170, 500, 60);

        logbutton_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/check-1-icon.png"))); // NOI18N
        Panel1.add(logbutton_label);
        logbutton_label.setBounds(340, 330, 50, 60);

        pass_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Unlock-icon.png"))); // NOI18N
        Panel1.add(pass_label);
        pass_label.setBounds(340, 280, 50, 60);

        user_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/User-icon.png"))); // NOI18N
        Panel1.add(user_label);
        user_label.setBounds(340, 230, 50, 60);

        btn_login.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_login.setForeground(new java.awt.Color(102, 102, 102));
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        Panel1.add(btn_login);
        btn_login.setBounds(400, 340, 290, 40);

        txt_password.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_password.setForeground(new java.awt.Color(51, 51, 51));
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });
        Panel1.add(txt_password);
        txt_password.setBounds(400, 290, 290, 40);

        txt_username.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_username.setForeground(new java.awt.Color(51, 51, 51));
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usernameKeyPressed(evt);
            }
        });
        Panel1.add(txt_username);
        txt_username.setBounds(400, 240, 290, 40);

        backgournd_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bc.jpg"))); // NOI18N
        Panel1.add(backgournd_image);
        backgournd_image.setBounds(0, 0, 2030, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2038, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 227, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        conn = Connector.ConnectDB();
        String sql = "SELECT * FROM LOG WHERE USERNAME = ? AND PASSWORD = ?";
        try{
           pst = conn.prepareStatement(sql); 
           pst.setString(1, txt_username.getText());
           pst.setString(2, txt_password.getText());
           rs = pst.executeQuery();
           if(rs.next()){
               if("admin".equals(txt_username.getText()) & "admin".equals(txt_password.getText())){
                    HomePage homePage = new HomePage();
                    homePage.setVisible(true);
                    rs.close();
                    pst.close();
                    dispose();
               }
               
               if("doctor".equals(txt_username.getText()) & "doctor".equals(txt_password.getText())){
                    DoctorMainPage docMainPage = new DoctorMainPage();
                    docMainPage.setVisible(true);
                    rs.close();
                    pst.close();
                    dispose();
               }
               
               if("reception".equals(txt_username.getText()) & "reception".equals(txt_password.getText())){
                    RepMainPage repMainPage = new RepMainPage();
                    repMainPage.setVisible(true);
                    rs.close();
                    pst.close();
                    dispose();
               }
               
               
           }else{
               JOptionPane.showMessageDialog(null, "Invalid Password or User Name", "Access Denied", JOptionPane.ERROR_MESSAGE);
           }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btn_loginActionPerformed

    private void txt_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyPressed
        int key = evt.getKeyCode();
        if(key ==  10){
            txt_password.requestFocus();
        }
    }//GEN-LAST:event_txt_usernameKeyPressed

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
        int key = evt.getKeyCode();
        if(key == 10){
            btn_login.requestFocus();
        }
    }//GEN-LAST:event_txt_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
            /* {
            */
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JLabel backgournd_image;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel logbutton_label;
    private javax.swing.JLabel pass_label;
    private javax.swing.JLabel title_label;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    private javax.swing.JLabel user_label;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
