/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import reception.AddP;
import reception.AddReceptionPage;
import reception.ViewReceptionPage;

/**
 *
 * @author mahad
 */
public class RepMainPage extends javax.swing.JFrame {

    Timer timer;
    
    public RepMainPage() {
        initComponents();
        ActionListener actionListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date date = new Date();
                DateFormat timeFormat = new SimpleDateFormat("hh:mm:ss aa");
                String time = timeFormat.format(date);
                curr_time_label.setText(time);
            }
        };
        timer = new Timer(1000, actionListener);
        timer.setInitialDelay(0);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reception_panel = new javax.swing.JPanel();
        add_btn = new javax.swing.JButton();
        set_appointment_btn1 = new javax.swing.JButton();
        set_appointment_btn = new javax.swing.JButton();
        Calendar = new com.toedter.calendar.JCalendar();
        curr_time_label = new javax.swing.JLabel();
        page_title_label = new javax.swing.JLabel();
        time_label = new javax.swing.JLabel();
        addP_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        view_btn = new javax.swing.JButton();
        view_btn3 = new javax.swing.JButton();
        background_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reception Management");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setResizable(false);

        reception_panel.setPreferredSize(new java.awt.Dimension(1050, 626));
        reception_panel.setLayout(null);

        add_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add_btn.setForeground(new java.awt.Color(102, 102, 102));
        add_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Add User Male_96px.png"))); // NOI18N
        add_btn.setText("Add");
        add_btn.setToolTipText("Add Doctor");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        reception_panel.add(add_btn);
        add_btn.setBounds(740, 110, 300, 180);

        set_appointment_btn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        set_appointment_btn1.setForeground(new java.awt.Color(102, 102, 102));
        set_appointment_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Calendar Plus_48px.png"))); // NOI18N
        set_appointment_btn1.setText("Appointment");
        set_appointment_btn1.setToolTipText("Appointment");
        set_appointment_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_appointment_btn1ActionPerformed(evt);
            }
        });
        reception_panel.add(set_appointment_btn1);
        set_appointment_btn1.setBounds(10, 340, 190, 60);

        set_appointment_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        set_appointment_btn.setForeground(new java.awt.Color(102, 102, 102));
        set_appointment_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/set appointment.png"))); // NOI18N
        set_appointment_btn.setText("Set Appointment");
        set_appointment_btn.setToolTipText("View Docor");
        set_appointment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_appointment_btnActionPerformed(evt);
            }
        });
        reception_panel.add(set_appointment_btn);
        set_appointment_btn.setBounds(10, 110, 340, 180);

        Calendar.setBackground(new java.awt.Color(255, 255, 255));
        Calendar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reception_panel.add(Calendar);
        Calendar.setBounds(570, 310, 470, 260);

        curr_time_label.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        curr_time_label.setForeground(new java.awt.Color(102, 102, 102));
        reception_panel.add(curr_time_label);
        curr_time_label.setBounds(870, 50, 170, 40);

        page_title_label.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 48)); // NOI18N
        page_title_label.setForeground(new java.awt.Color(255, 255, 255));
        page_title_label.setText("Reception Panel");
        reception_panel.add(page_title_label);
        page_title_label.setBounds(20, 30, 550, 70);

        time_label.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        time_label.setForeground(new java.awt.Color(102, 102, 102));
        time_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/Clock-Forward-icon.png"))); // NOI18N
        reception_panel.add(time_label);
        time_label.setBounds(810, 40, 60, 50);

        addP_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addP_btn.setForeground(new java.awt.Color(102, 102, 102));
        addP_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/patient.png"))); // NOI18N
        addP_btn.setText("Add Patient");
        addP_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addP_btnActionPerformed(evt);
            }
        });
        reception_panel.add(addP_btn);
        addP_btn.setBounds(10, 400, 190, 60);

        logout_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(102, 102, 102));
        logout_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/switch-turn-off-icon.png"))); // NOI18N
        logout_btn.setText("LogOut      ");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        reception_panel.add(logout_btn);
        logout_btn.setBounds(10, 520, 190, 60);

        view_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        view_btn.setForeground(new java.awt.Color(102, 102, 102));
        view_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/view.png"))); // NOI18N
        view_btn.setText("View Receptionist");
        view_btn.setToolTipText("View Docor");
        view_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_btnActionPerformed(evt);
            }
        });
        reception_panel.add(view_btn);
        view_btn.setBounds(360, 110, 370, 180);

        view_btn3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        view_btn3.setForeground(new java.awt.Color(102, 102, 102));
        view_btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/view2.png"))); // NOI18N
        view_btn3.setText("View            ");
        view_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_btn3ActionPerformed(evt);
            }
        });
        reception_panel.add(view_btn3);
        view_btn3.setBounds(10, 460, 190, 60);

        background_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reception/AllBackGrondPic.jpg"))); // NOI18N
        reception_panel.add(background_label);
        background_label.setBounds(0, 0, 1050, 626);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(reception_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(reception_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addP_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addP_btnActionPerformed
        AddP vrp = new AddP();
        vrp.setVisible(true);
        dispose();
    }//GEN-LAST:event_addP_btnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logout_btnActionPerformed

    private void view_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btnActionPerformed
        ViewReception vrp = new ViewReception();
        vrp.setVisible(true);
        dispose();
    }//GEN-LAST:event_view_btnActionPerformed

    private void set_appointment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_appointment_btnActionPerformed
        ChooseDoctorPage cdp = new ChooseDoctorPage();
        cdp.setVisible(true);
        dispose();
    }//GEN-LAST:event_set_appointment_btnActionPerformed

    private void set_appointment_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_appointment_btn1ActionPerformed
        ChooseDoctorPage cdp = new ChooseDoctorPage();
        cdp.setVisible(true);
        dispose();
    }//GEN-LAST:event_set_appointment_btn1ActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        AddRep addrp = new AddRep();
        addrp.setVisible(true);
        dispose();
    }//GEN-LAST:event_add_btnActionPerformed

    private void view_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btn3ActionPerformed
        ViewReception vrp = new ViewReception();
        vrp.setVisible(true);
        dispose();
    }//GEN-LAST:event_view_btn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RepMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RepMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RepMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RepMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RepMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar Calendar;
    private javax.swing.JButton addP_btn;
    private javax.swing.JButton add_btn;
    private javax.swing.JLabel background_label;
    private javax.swing.JLabel curr_time_label;
    private javax.swing.JButton logout_btn;
    private javax.swing.JLabel page_title_label;
    private javax.swing.JPanel reception_panel;
    private javax.swing.JButton set_appointment_btn;
    private javax.swing.JButton set_appointment_btn1;
    private javax.swing.JLabel time_label;
    private javax.swing.JButton view_btn;
    private javax.swing.JButton view_btn3;
    // End of variables declaration//GEN-END:variables
}
