/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reception;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import main.Connector;
import main.Login;
import main.RepMainPage;

/**
 *
 * @author mahad
 */
public class AddP extends javax.swing.JFrame {

    private Connection conn = null;
    private PreparedStatement pst = null;
    
    
    public AddP() {
        initComponents();
        setIconImage();
    }
    
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bradcum_label = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        logOut_btn = new javax.swing.JButton();
        serialNo_label = new javax.swing.JLabel();
        serialNo_txt = new javax.swing.JTextField();
        id_label = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        date_label = new javax.swing.JLabel();
        date_date = new com.toedter.calendar.JDateChooser();
        name_label = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        age_label = new javax.swing.JLabel();
        age_txt = new javax.swing.JTextField();
        disease_label = new javax.swing.JLabel();
        disease_txt = new javax.swing.JTextField();
        phone_label = new javax.swing.JLabel();
        phone_txt = new javax.swing.JTextField();
        status_label = new javax.swing.JLabel();
        status_combox = new javax.swing.JComboBox<>();
        blood_combox = new javax.swing.JComboBox<>();
        blood_label = new javax.swing.JLabel();
        roomNo_txt = new javax.swing.JTextField();
        roomNo_label = new javax.swing.JLabel();
        gender_label = new javax.swing.JLabel();
        gender_combox = new javax.swing.JComboBox<>();
        address_txt = new javax.swing.JTextField();
        patient_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        address_label = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        email_label = new javax.swing.JLabel();
        bg_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Patient");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setPreferredSize(new java.awt.Dimension(1050, 626));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 626));
        jPanel1.setLayout(null);

        bradcum_label.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 30)); // NOI18N
        bradcum_label.setForeground(new java.awt.Color(255, 255, 255));
        bradcum_label.setText("Patient Panel >> Add Patient");
        jPanel1.add(bradcum_label);
        bradcum_label.setBounds(10, 30, 510, 70);

        back_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(102, 102, 102));
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/arrow-back-icon.png"))); // NOI18N
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn);
        back_btn.setBounds(720, 30, 160, 60);

        logOut_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logOut_btn.setForeground(new java.awt.Color(102, 102, 102));
        logOut_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/switch-turn-off-icon.png"))); // NOI18N
        logOut_btn.setText("Log Out");
        logOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btnActionPerformed(evt);
            }
        });
        jPanel1.add(logOut_btn);
        logOut_btn.setBounds(880, 30, 160, 60);

        serialNo_label.setBackground(new java.awt.Color(255, 255, 255));
        serialNo_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        serialNo_label.setForeground(new java.awt.Color(0, 51, 51));
        serialNo_label.setText("Serial No :");
        jPanel1.add(serialNo_label);
        serialNo_label.setBounds(40, 140, 130, 40);

        serialNo_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        serialNo_txt.setForeground(new java.awt.Color(51, 51, 51));
        serialNo_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                serialNo_txtKeyPressed(evt);
            }
        });
        jPanel1.add(serialNo_txt);
        serialNo_txt.setBounds(170, 140, 310, 40);

        id_label.setBackground(new java.awt.Color(255, 255, 255));
        id_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        id_label.setForeground(new java.awt.Color(0, 51, 51));
        id_label.setText("ID :");
        jPanel1.add(id_label);
        id_label.setBounds(120, 190, 50, 40);

        id_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        id_txt.setForeground(new java.awt.Color(51, 51, 51));
        id_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                id_txtKeyPressed(evt);
            }
        });
        jPanel1.add(id_txt);
        id_txt.setBounds(170, 190, 310, 40);

        date_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        date_label.setForeground(new java.awt.Color(0, 51, 51));
        date_label.setText("Date :");
        jPanel1.add(date_label);
        date_label.setBounds(90, 240, 80, 40);

        date_date.setForeground(new java.awt.Color(51, 51, 51));
        date_date.setDateFormatString("yyyy-MM-dd");
        date_date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(date_date);
        date_date.setBounds(170, 240, 180, 40);

        name_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name_label.setForeground(new java.awt.Color(0, 51, 51));
        name_label.setText("Name :");
        jPanel1.add(name_label);
        name_label.setBounds(80, 290, 90, 40);

        name_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name_txt.setForeground(new java.awt.Color(51, 51, 51));
        name_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                name_txtKeyPressed(evt);
            }
        });
        jPanel1.add(name_txt);
        name_txt.setBounds(170, 290, 310, 40);

        age_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        age_label.setForeground(new java.awt.Color(0, 51, 51));
        age_label.setText("Age :");
        jPanel1.add(age_label);
        age_label.setBounds(100, 340, 70, 40);

        age_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        age_txt.setForeground(new java.awt.Color(51, 51, 51));
        age_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                age_txtKeyPressed(evt);
            }
        });
        jPanel1.add(age_txt);
        age_txt.setBounds(170, 340, 150, 40);

        disease_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        disease_label.setForeground(new java.awt.Color(0, 51, 51));
        disease_label.setText("Disease :");
        jPanel1.add(disease_label);
        disease_label.setBounds(50, 390, 120, 40);

        disease_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        disease_txt.setForeground(new java.awt.Color(51, 51, 51));
        disease_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                disease_txtKeyPressed(evt);
            }
        });
        jPanel1.add(disease_txt);
        disease_txt.setBounds(170, 390, 310, 40);

        phone_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        phone_label.setForeground(new java.awt.Color(0, 51, 51));
        phone_label.setText("Phone :");
        jPanel1.add(phone_label);
        phone_label.setBounds(70, 440, 100, 40);

        phone_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phone_txt.setForeground(new java.awt.Color(51, 51, 51));
        phone_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phone_txtKeyPressed(evt);
            }
        });
        jPanel1.add(phone_txt);
        phone_txt.setBounds(170, 440, 310, 40);

        status_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        status_label.setForeground(new java.awt.Color(0, 51, 51));
        status_label.setText("Maritial Status :");
        jPanel1.add(status_label);
        status_label.setBounds(500, 390, 200, 40);

        status_combox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        status_combox.setForeground(new java.awt.Color(102, 102, 102));
        status_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Status", "Single", "Married", "Divorced", "" }));
        jPanel1.add(status_combox);
        status_combox.setBounds(700, 390, 280, 40);

        blood_combox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        blood_combox.setForeground(new java.awt.Color(102, 102, 102));
        blood_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Blood Group", "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-", "", "" }));
        jPanel1.add(blood_combox);
        blood_combox.setBounds(700, 340, 280, 40);

        blood_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        blood_label.setForeground(new java.awt.Color(204, 0, 0));
        blood_label.setText("Blood Group :");
        jPanel1.add(blood_label);
        blood_label.setBounds(520, 340, 180, 40);

        roomNo_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roomNo_txt.setForeground(new java.awt.Color(51, 51, 51));
        roomNo_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                roomNo_txtKeyPressed(evt);
            }
        });
        jPanel1.add(roomNo_txt);
        roomNo_txt.setBounds(700, 290, 150, 40);

        roomNo_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        roomNo_label.setText("Room No :");
        jPanel1.add(roomNo_label);
        roomNo_label.setBounds(560, 290, 140, 40);

        gender_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        gender_label.setText("Gender :");
        jPanel1.add(gender_label);
        gender_label.setBounds(590, 240, 110, 40);

        gender_combox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        gender_combox.setForeground(new java.awt.Color(102, 102, 102));
        gender_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "FeMale", "Zhe", "" }));
        jPanel1.add(gender_combox);
        gender_combox.setBounds(700, 240, 280, 40);

        address_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        address_txt.setForeground(new java.awt.Color(51, 51, 51));
        address_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                address_txtKeyPressed(evt);
            }
        });
        jPanel1.add(address_txt);
        address_txt.setBounds(700, 190, 310, 40);

        patient_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        patient_btn.setForeground(new java.awt.Color(102, 102, 102));
        patient_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/patient.png"))); // NOI18N
        patient_btn.setText("View Patient");
        patient_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patient_btnActionPerformed(evt);
            }
        });
        jPanel1.add(patient_btn);
        patient_btn.setBounds(610, 490, 210, 60);

        save_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        save_btn.setForeground(new java.awt.Color(102, 102, 102));
        save_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Floppy-icon.png"))); // NOI18N
        save_btn.setText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        jPanel1.add(save_btn);
        save_btn.setBounds(820, 490, 160, 60);

        address_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        address_label.setText("Address :");
        jPanel1.add(address_label);
        address_label.setBounds(580, 190, 120, 40);

        email_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email_txt.setForeground(new java.awt.Color(51, 51, 51));
        email_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                email_txtKeyPressed(evt);
            }
        });
        jPanel1.add(email_txt);
        email_txt.setBounds(700, 140, 310, 40);

        email_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        email_label.setForeground(new java.awt.Color(0, 51, 51));
        email_label.setText("Email :");
        jPanel1.add(email_label);
        email_label.setBounds(610, 140, 90, 40);

        bg_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/AllBackGrondPic - Copy.jpg"))); // NOI18N
        jPanel1.add(bg_label);
        bg_label.setBounds(0, 0, 1050, 620);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void email_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_email_txtKeyPressed
        int key = evt.getKeyCode();
        if(key ==  10){
            address_txt.requestFocus();
        }
    }//GEN-LAST:event_email_txtKeyPressed

    private void address_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_address_txtKeyPressed
        int key = evt.getKeyCode();
        if(key ==  10){
            address_txt.requestFocus();
        }
    }//GEN-LAST:event_address_txtKeyPressed

    private void roomNo_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roomNo_txtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomNo_txtKeyPressed

    private void phone_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_txtKeyPressed
        int key = evt.getKeyCode();
        if(key ==  10){
            email_txt.requestFocus();
        }
    }//GEN-LAST:event_phone_txtKeyPressed

    private void disease_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_disease_txtKeyPressed
        int key = evt.getKeyCode();
        if(key == 10){
            phone_txt.requestFocus();
        }
    }//GEN-LAST:event_disease_txtKeyPressed

    private void age_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_age_txtKeyPressed
        int key = evt.getKeyCode();
        if(key == 10){
            disease_txt.requestFocus();
        }
    }//GEN-LAST:event_age_txtKeyPressed

    private void name_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name_txtKeyPressed
        int key = evt.getKeyCode();
        if(key ==  10){
            age_txt.requestFocus();
        }
    }//GEN-LAST:event_name_txtKeyPressed

    private void id_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_txtKeyPressed
        int key = evt.getKeyCode();
        if(key ==  10){
            date_date.requestFocus();
        }
    }//GEN-LAST:event_id_txtKeyPressed

    private void serialNo_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serialNo_txtKeyPressed
        int key = evt.getKeyCode();
        if(key == 10){
            id_txt.requestFocus();
        }
    }//GEN-LAST:event_serialNo_txtKeyPressed

    private void logOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btnActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOut_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        RepMainPage php = new RepMainPage();
        php.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void patient_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patient_btnActionPerformed
        ViewP vp = new ViewP();
        vp.setVisible(true);
        dispose();
    }//GEN-LAST:event_patient_btnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        conn = Connector.ConnectDB();
        if(conn != null){
            String serialNO = serialNo_txt.getText();
            String id = id_txt.getText();
            String date = ((JTextField)date_date.getDateEditor().getUiComponent()).getText();
            String name = name_txt.getText();
            int age = Integer.parseInt(age_txt.getText());
            String disease = disease_txt.getText();
            String phone = phone_txt.getText();
            String email = email_txt.getText();
            String address = address_txt.getText();
            String gender = (String) gender_combox.getSelectedItem();
            String roomNo = roomNo_txt.getText();
            String blood = (String) blood_combox.getSelectedItem();
            String status = (String) status_combox.getSelectedItem();
            String sql = "INSERT INTO `patient` (`Serial`, `ID`, `Date`, `Name`, `Age`, `Disease`,  `Phone`, `Email`, `Address`, `Gender`, `Room`, `BG`, `Status`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            try{
                pst = conn.prepareStatement(sql);
                pst.setString(1, serialNO);
                pst.setString(2, id);
                pst.setString(3, date);
                pst.setString(4, name);
                pst.setInt(5, age);
                pst.setString(6, disease);
                pst.setString(7, phone);
                pst.setString(8, email);
                pst.setString(9, address);
                pst.setString(10, gender);
                pst.setString(11, roomNo);
                pst.setString(12, blood);
                pst.setString(13, status);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Saved Successfully!");

            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_save_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address_label;
    private javax.swing.JTextField address_txt;
    private javax.swing.JLabel age_label;
    private javax.swing.JTextField age_txt;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel bg_label;
    private javax.swing.JComboBox<String> blood_combox;
    private javax.swing.JLabel blood_label;
    private javax.swing.JLabel bradcum_label;
    private com.toedter.calendar.JDateChooser date_date;
    private javax.swing.JLabel date_label;
    private javax.swing.JLabel disease_label;
    private javax.swing.JTextField disease_txt;
    private javax.swing.JLabel email_label;
    private javax.swing.JTextField email_txt;
    private javax.swing.JComboBox<String> gender_combox;
    private javax.swing.JLabel gender_label;
    private javax.swing.JLabel id_label;
    private javax.swing.JTextField id_txt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logOut_btn;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField name_txt;
    private javax.swing.JButton patient_btn;
    private javax.swing.JLabel phone_label;
    private javax.swing.JTextField phone_txt;
    private javax.swing.JLabel roomNo_label;
    private javax.swing.JTextField roomNo_txt;
    private javax.swing.JButton save_btn;
    private javax.swing.JLabel serialNo_label;
    private javax.swing.JTextField serialNo_txt;
    private javax.swing.JComboBox<String> status_combox;
    private javax.swing.JLabel status_label;
    // End of variables declaration//GEN-END:variables
}
