/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doctor;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import main.Connector;
import main.HomePage;
import main.Login;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author mahad
 */
public final class UpdateDoctor extends javax.swing.JFrame {

    private Connection conn = null;
    private PreparedStatement pst = null;
    private ResultSet rs = null;
    
    public UpdateDoctor() {
        initComponents();
        fetch_table();
        setIconImage();
    }
    
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
    private void update_table(){
        try{
            String sql = "SELECT * FROM doctor";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            doctor_table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void fetch_table(){
        conn = Connector.ConnectDB();
        try{
            String sql = "SELECT * FROM doctor";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            doctor_table.setModel(DbUtils.resultSetToTableModel(rs));
            doctor_table.setAutoResizeMode(doctor_table.AUTO_RESIZE_OFF);
            doctor_table.getColumnModel().getColumn(0).setPreferredWidth(68);
            doctor_table.getColumnModel().getColumn(1).setPreferredWidth(187);
            doctor_table.getColumnModel().getColumn(2).setPreferredWidth(120);
            doctor_table.getColumnModel().getColumn(3).setPreferredWidth(33);
            doctor_table.getColumnModel().getColumn(4).setPreferredWidth(53);
            doctor_table.getColumnModel().getColumn(5).setPreferredWidth(185);
            doctor_table.getColumnModel().getColumn(6).setPreferredWidth(110);
            doctor_table.getColumnModel().getColumn(7).setPreferredWidth(90);
            doctor_table.getColumnModel().getColumn(8).setPreferredWidth(80);
            doctor_table.getColumnModel().getColumn(9).setPreferredWidth(40);
            doctor_table.getColumnModel().getColumn(10).setPreferredWidth(58);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        update_panel = new javax.swing.JPanel();
        add_btn = new javax.swing.JButton();
        table = new javax.swing.JScrollPane();
        doctor_table = new javax.swing.JTable();
        status_txt = new javax.swing.JTextField();
        blood_txt = new javax.swing.JTextField();
        date_txt = new javax.swing.JTextField();
        department_txt = new javax.swing.JTextField();
        phone_txt = new javax.swing.JTextField();
        address_txt = new javax.swing.JTextField();
        gender_txt = new javax.swing.JTextField();
        age_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        name_txt = new javax.swing.JTextField();
        id_txt = new javax.swing.JTextField();
        update_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        home_btn = new javax.swing.JButton();
        logOut_btn = new javax.swing.JButton();
        bradcum_label = new javax.swing.JLabel();
        background_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update WIndow");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setPreferredSize(new java.awt.Dimension(1050, 626));
        setResizable(false);
        setSize(new java.awt.Dimension(1050, 626));

        update_panel.setPreferredSize(new java.awt.Dimension(1050, 626));
        update_panel.setLayout(null);

        add_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add_btn.setForeground(new java.awt.Color(102, 102, 102));
        add_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/Actions-contact-new-icon.png"))); // NOI18N
        add_btn.setText("Add");
        add_btn.setToolTipText("");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        update_panel.add(add_btn);
        add_btn.setBounds(740, 530, 140, 60);

        doctor_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11"
            }
        ));
        doctor_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctor_tableMouseClicked(evt);
            }
        });
        table.setViewportView(doctor_table);

        update_panel.add(table);
        table.setBounds(10, 120, 1030, 410);
        update_panel.add(status_txt);
        status_txt.setBounds(980, 90, 60, 30);
        update_panel.add(blood_txt);
        blood_txt.setBounds(940, 90, 40, 30);
        update_panel.add(date_txt);
        date_txt.setBounds(860, 90, 80, 30);
        update_panel.add(department_txt);
        department_txt.setBounds(660, 90, 110, 30);
        update_panel.add(phone_txt);
        phone_txt.setBounds(770, 90, 90, 30);
        update_panel.add(address_txt);
        address_txt.setBounds(470, 90, 190, 30);
        update_panel.add(gender_txt);
        gender_txt.setBounds(420, 90, 53, 30);
        update_panel.add(age_txt);
        age_txt.setBounds(390, 90, 33, 30);

        email_txt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtActionPerformed(evt);
            }
        });
        update_panel.add(email_txt);
        email_txt.setBounds(270, 90, 120, 30);
        update_panel.add(name_txt);
        name_txt.setBounds(80, 90, 190, 30);
        update_panel.add(id_txt);
        id_txt.setBounds(10, 90, 70, 30);

        update_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update_btn.setForeground(new java.awt.Color(51, 51, 51));
        update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/document-edit-icon (1).png"))); // NOI18N
        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        update_panel.add(update_btn);
        update_btn.setBounds(880, 530, 160, 60);

        back_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(102, 102, 102));
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/arrow-back-icon.png"))); // NOI18N
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        update_panel.add(back_btn);
        back_btn.setBounds(560, 20, 160, 60);

        home_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        home_btn.setForeground(new java.awt.Color(102, 102, 102));
        home_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/Home-icon (1).png"))); // NOI18N
        home_btn.setText("Home");
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        update_panel.add(home_btn);
        home_btn.setBounds(720, 20, 160, 60);

        logOut_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logOut_btn.setForeground(new java.awt.Color(102, 102, 102));
        logOut_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/switch-turn-off-icon.png"))); // NOI18N
        logOut_btn.setText("Log Out");
        logOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btnActionPerformed(evt);
            }
        });
        update_panel.add(logOut_btn);
        logOut_btn.setBounds(880, 20, 160, 60);

        bradcum_label.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        bradcum_label.setForeground(new java.awt.Color(255, 255, 255));
        bradcum_label.setText("Doctor Panel >> Update Doctor");
        update_panel.add(bradcum_label);
        bradcum_label.setBounds(10, 20, 450, 60);

        background_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/AllBackGrondPic.jpg"))); // NOI18N
        update_panel.add(background_label);
        background_label.setBounds(0, 0, 1050, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(update_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(update_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        DoctorHomePage dhp = new DoctorHomePage();
        dhp.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        dispose();
    }//GEN-LAST:event_home_btnActionPerformed

    private void logOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btnActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOut_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        
        //try the 1st one
        try{
            String id = id_txt.getText();
            String name = name_txt.getText();
            String email = email_txt.getText();
            String age = age_txt.getText();
            String gender = gender_txt.getText();
            String address = address_txt.getText();
            String department = department_txt.getText();
            String phone = phone_txt.getText();
            String date = date_txt.getText();
            String blood = blood_txt.getText();
            String status = status_txt.getText();
            String sql = "UPDATE `doctor` SET `ID` = '"+id+"', `Name` = '"+name+"', `Email` = '"+email+"', `Age` = '"+age+"', `Gender` = '"+gender+"', `Address` = '"+address+"', `Department` = '"+department+"', `Phone` = '"+phone+"', `Join Date` = '"+date+"', `Blood Group` = '"+blood+"', `Status` = '"+status+"' WHERE `doctor`.`ID` = '"+id+"'";
            //*/
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated Successfully");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        update_table();
        doctor_table.setAutoResizeMode(doctor_table.AUTO_RESIZE_OFF);
            doctor_table.getColumnModel().getColumn(0).setPreferredWidth(68);
            doctor_table.getColumnModel().getColumn(1).setPreferredWidth(187);
            doctor_table.getColumnModel().getColumn(2).setPreferredWidth(120);
            doctor_table.getColumnModel().getColumn(3).setPreferredWidth(33);
            doctor_table.getColumnModel().getColumn(4).setPreferredWidth(53);
            doctor_table.getColumnModel().getColumn(5).setPreferredWidth(185);
            doctor_table.getColumnModel().getColumn(6).setPreferredWidth(110);
            doctor_table.getColumnModel().getColumn(7).setPreferredWidth(90);
            doctor_table.getColumnModel().getColumn(8).setPreferredWidth(80);
            doctor_table.getColumnModel().getColumn(9).setPreferredWidth(40);
            doctor_table.getColumnModel().getColumn(10).setPreferredWidth(58);
    }//GEN-LAST:event_update_btnActionPerformed

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtActionPerformed

    private void doctor_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctor_tableMouseClicked
        try{
            int row = doctor_table.getSelectedRow();
            String tableClick = (doctor_table.getModel().getValueAt(row, 0).toString());
            String sql = "SELECT * FROM doctor WHERE ID = '" + tableClick + "' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){
                String id = rs.getString("ID");
                id_txt.setText(id);
                String name = rs.getString("Name");
                name_txt.setText(name);
                String email = rs.getString("Email");
                email_txt.setText(email);
                String age = rs.getString("Age");
                age_txt.setText(age);
                String gender = rs.getString("Gender");
                gender_txt.setText(gender);
                String adderss = rs.getString("Address");
                address_txt.setText(adderss);
                String department = rs.getString("Department");
                department_txt.setText(department);
                String phone = rs.getString("Phone");
                phone_txt.setText(phone);
                String date = rs.getString("Join Date");
                date_txt.setText(date);
                String blood = rs.getString("Blood Group");
                blood_txt.setText(blood);
                String status = rs.getString("Status");
                status_txt.setText(status);
                }
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_doctor_tableMouseClicked

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        AddDoctor addDoc = new AddDoctor();
        addDoc.setVisible(true);
        dispose();
    }//GEN-LAST:event_add_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JTextField address_txt;
    private javax.swing.JTextField age_txt;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel background_label;
    private javax.swing.JTextField blood_txt;
    private javax.swing.JLabel bradcum_label;
    private javax.swing.JTextField date_txt;
    private javax.swing.JTextField department_txt;
    private javax.swing.JTable doctor_table;
    private javax.swing.JTextField email_txt;
    private javax.swing.JTextField gender_txt;
    private javax.swing.JButton home_btn;
    private javax.swing.JTextField id_txt;
    private javax.swing.JButton logOut_btn;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField phone_txt;
    private javax.swing.JTextField status_txt;
    private javax.swing.JScrollPane table;
    private javax.swing.JButton update_btn;
    private javax.swing.JPanel update_panel;
    // End of variables declaration//GEN-END:variables
}
