/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doctor;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import main.Connector;
import main.HomePage;
import main.Login;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author mahad
 */
public class ViewDoctor extends javax.swing.JFrame {

    private Connection conn = null;
    private PreparedStatement pst = null;
    private ResultSet rs = null;
    
    public ViewDoctor() {
        initComponents();
        conn = Connector.ConnectDB();
        fetch_table();
        setIconImage();
    }
    
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
    
    private void fetch_table(){
        try{
            String sql = "SELECT * FROM doctor";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            doctor_table.setModel(DbUtils.resultSetToTableModel(rs));
            doctor_table.setAutoResizeMode(doctor_table.AUTO_RESIZE_OFF);
            doctor_table.getColumnModel().getColumn(0).setPreferredWidth(68);
            doctor_table.getColumnModel().getColumn(1).setPreferredWidth(187);
            doctor_table.getColumnModel().getColumn(2).setPreferredWidth(120);
            doctor_table.getColumnModel().getColumn(3).setPreferredWidth(33);
            doctor_table.getColumnModel().getColumn(4).setPreferredWidth(53);
            doctor_table.getColumnModel().getColumn(5).setPreferredWidth(185);
            doctor_table.getColumnModel().getColumn(6).setPreferredWidth(110);
            doctor_table.getColumnModel().getColumn(7).setPreferredWidth(90);
            doctor_table.getColumnModel().getColumn(8).setPreferredWidth(80);
            doctor_table.getColumnModel().getColumn(9).setPreferredWidth(40);
            doctor_table.getColumnModel().getColumn(10).setPreferredWidth(58);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        view_doctor_panel = new javax.swing.JPanel();
        add_btn = new javax.swing.JButton();
        status_txt = new javax.swing.JTextField();
        blood_txt = new javax.swing.JTextField();
        date_txt = new javax.swing.JTextField();
        department_txt = new javax.swing.JTextField();
        phone_txt = new javax.swing.JTextField();
        address_txt = new javax.swing.JTextField();
        gender_txt = new javax.swing.JTextField();
        age_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        name_txt = new javax.swing.JTextField();
        id_txt = new javax.swing.JTextField();
        view_table = new javax.swing.JScrollPane();
        doctor_table = new javax.swing.JTable();
        logOut_btn = new javax.swing.JButton();
        home_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        bradcum_label = new javax.swing.JLabel();
        background_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Doctor");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(1050, 626));

        view_doctor_panel.setPreferredSize(new java.awt.Dimension(1050, 626));
        view_doctor_panel.setLayout(null);

        add_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add_btn.setForeground(new java.awt.Color(102, 102, 102));
        add_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/Actions-contact-new-icon.png"))); // NOI18N
        add_btn.setText("Add");
        add_btn.setToolTipText("");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        view_doctor_panel.add(add_btn);
        add_btn.setBounds(420, 30, 140, 60);
        view_doctor_panel.add(status_txt);
        status_txt.setBounds(980, 100, 60, 30);
        view_doctor_panel.add(blood_txt);
        blood_txt.setBounds(940, 100, 40, 30);
        view_doctor_panel.add(date_txt);
        date_txt.setBounds(860, 100, 80, 30);
        view_doctor_panel.add(department_txt);
        department_txt.setBounds(660, 100, 110, 30);
        view_doctor_panel.add(phone_txt);
        phone_txt.setBounds(770, 100, 90, 30);
        view_doctor_panel.add(address_txt);
        address_txt.setBounds(470, 100, 190, 30);
        view_doctor_panel.add(gender_txt);
        gender_txt.setBounds(420, 100, 53, 30);
        view_doctor_panel.add(age_txt);
        age_txt.setBounds(390, 100, 33, 30);

        email_txt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtActionPerformed(evt);
            }
        });
        view_doctor_panel.add(email_txt);
        email_txt.setBounds(270, 100, 120, 30);
        view_doctor_panel.add(name_txt);
        name_txt.setBounds(80, 100, 190, 30);
        view_doctor_panel.add(id_txt);
        id_txt.setBounds(10, 100, 70, 30);

        view_table.setForeground(new java.awt.Color(51, 51, 51));

        doctor_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Department", "Email", "Phone", "Address", "Age", "Gender", "Date", "Blood Gr", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        doctor_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctor_tableMouseClicked(evt);
            }
        });
        view_table.setViewportView(doctor_table);
        if (doctor_table.getColumnModel().getColumnCount() > 0) {
            doctor_table.getColumnModel().getColumn(0).setResizable(false);
            doctor_table.getColumnModel().getColumn(0).setPreferredWidth(70);
            doctor_table.getColumnModel().getColumn(1).setResizable(false);
            doctor_table.getColumnModel().getColumn(1).setPreferredWidth(190);
            doctor_table.getColumnModel().getColumn(2).setResizable(false);
            doctor_table.getColumnModel().getColumn(2).setPreferredWidth(120);
            doctor_table.getColumnModel().getColumn(3).setResizable(false);
            doctor_table.getColumnModel().getColumn(3).setPreferredWidth(100);
            doctor_table.getColumnModel().getColumn(4).setResizable(false);
            doctor_table.getColumnModel().getColumn(4).setPreferredWidth(100);
            doctor_table.getColumnModel().getColumn(5).setResizable(false);
            doctor_table.getColumnModel().getColumn(5).setPreferredWidth(150);
            doctor_table.getColumnModel().getColumn(6).setResizable(false);
            doctor_table.getColumnModel().getColumn(6).setPreferredWidth(50);
            doctor_table.getColumnModel().getColumn(7).setResizable(false);
            doctor_table.getColumnModel().getColumn(7).setPreferredWidth(70);
            doctor_table.getColumnModel().getColumn(8).setResizable(false);
            doctor_table.getColumnModel().getColumn(8).setPreferredWidth(70);
            doctor_table.getColumnModel().getColumn(9).setResizable(false);
            doctor_table.getColumnModel().getColumn(9).setPreferredWidth(100);
            doctor_table.getColumnModel().getColumn(10).setResizable(false);
            doctor_table.getColumnModel().getColumn(10).setPreferredWidth(100);
        }

        view_doctor_panel.add(view_table);
        view_table.setBounds(10, 132, 1030, 470);

        logOut_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logOut_btn.setForeground(new java.awt.Color(102, 102, 102));
        logOut_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/switch-turn-off-icon.png"))); // NOI18N
        logOut_btn.setText("Log Out");
        logOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btnActionPerformed(evt);
            }
        });
        view_doctor_panel.add(logOut_btn);
        logOut_btn.setBounds(880, 30, 160, 60);

        home_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        home_btn.setForeground(new java.awt.Color(102, 102, 102));
        home_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/Home-icon (1).png"))); // NOI18N
        home_btn.setText("Home");
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        view_doctor_panel.add(home_btn);
        home_btn.setBounds(720, 30, 160, 60);

        back_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(102, 102, 102));
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/arrow-back-icon.png"))); // NOI18N
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        view_doctor_panel.add(back_btn);
        back_btn.setBounds(560, 30, 160, 60);

        bradcum_label.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        bradcum_label.setForeground(new java.awt.Color(255, 255, 255));
        bradcum_label.setText("Doctor Panel >> View Doctor");
        view_doctor_panel.add(bradcum_label);
        bradcum_label.setBounds(10, 30, 390, 60);

        background_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/AllBackGrondPic.jpg"))); // NOI18N
        view_doctor_panel.add(background_label);
        background_label.setBounds(0, 0, 1050, 620);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(view_doctor_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(view_doctor_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        DoctorHomePage dhp = new DoctorHomePage();
        dhp.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        dispose();
    }//GEN-LAST:event_home_btnActionPerformed

    private void logOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btnActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOut_btnActionPerformed

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtActionPerformed

    private void doctor_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctor_tableMouseClicked
        try{
            int row = doctor_table.getSelectedRow();
            String tableClick = (doctor_table.getModel().getValueAt(row, 0).toString());
            String sql = "SELECT * FROM doctor WHERE ID = '" + tableClick + "' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){
                String id = rs.getString("ID");
                id_txt.setText(id);
                String name = rs.getString("Name");
                name_txt.setText(name);
                String email = rs.getString("Email");
                email_txt.setText(email);
                String age = rs.getString("Age");
                age_txt.setText(age);
                String gender = rs.getString("Gender");
                gender_txt.setText(gender);
                String adderss = rs.getString("Address");
                address_txt.setText(adderss);
                String department = rs.getString("Department");
                department_txt.setText(department);
                String phone = rs.getString("Phone");
                phone_txt.setText(phone);
                String date = rs.getString("Join Date");
                date_txt.setText(date);
                String blood = rs.getString("Blood Group");
                blood_txt.setText(blood);
                String status = rs.getString("Status");
                status_txt.setText(status);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_doctor_tableMouseClicked

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        AddDoctor addDoc = new AddDoctor();
        addDoc.setVisible(true);
        dispose();
    }//GEN-LAST:event_add_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JTextField address_txt;
    private javax.swing.JTextField age_txt;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel background_label;
    private javax.swing.JTextField blood_txt;
    private javax.swing.JLabel bradcum_label;
    private javax.swing.JTextField date_txt;
    private javax.swing.JTextField department_txt;
    private javax.swing.JTable doctor_table;
    private javax.swing.JTextField email_txt;
    private javax.swing.JTextField gender_txt;
    private javax.swing.JButton home_btn;
    private javax.swing.JTextField id_txt;
    private javax.swing.JButton logOut_btn;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField phone_txt;
    private javax.swing.JTextField status_txt;
    private javax.swing.JPanel view_doctor_panel;
    private javax.swing.JScrollPane view_table;
    // End of variables declaration//GEN-END:variables
}
